# This workflow will lint the training code and train the model when the training code has been changed
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python model training

on:
  push:
    branches: [ "main" ]
    paths:
      - src/train/train.py
      - src/train/data.csv

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -r src/train/requirements.txt
        
    - name: Lint with pylint
      run: |
        pylint src/train/train.py

    - name: Train model
      if: ${{ github.event_name == 'push' }}
      run: python src/train/train.py

    - name: Add model file to repository
      if: ${{ github.event_name == 'push' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update trained model file"
        git push -u origin main
